name: Deploy Production

on:
  workflow_dispatch:
    inputs:
      source:
        description: Deploy Production
        required: false
        default: devl

permissions:
  contents: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.source }}
          fetch-depth: 0

      - name: Fetch current main
        run: git fetch origin main || true

      - name: Fast-forward main to source
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/main; then
            if git merge-base --is-ancestor origin/main HEAD; then
              git push origin HEAD:main
            else
              echo "Not a fast-forward. Rebase devl or use force input."
              exit 1
            fi
          else
            git push origin HEAD:main
          fi
