name: Deploy Production

on:
  workflow_dispatch:
    inputs:
      source:
        description: Deploy Production
        required: false
        default: devl

permissions:
  contents: write
  pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.source }}
          fetch-depth: 0

      - name: Fetch main branch
        run: git fetch origin main

      - name: Check if there are changes to promote
        id: check_changes
        run: |
          if git diff --quiet origin/main HEAD; then
            echo "No changes to promote from ${{ github.event.inputs.source }} to main"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes found to promote from ${{ github.event.inputs.source }} to main"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create temporary file to trigger PR
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          # Create a temporary commit to ensure PR creation works
          echo "# Production Deployment - $(date)" > DEPLOYMENT.md
          echo "Promoting changes from ${{ github.event.inputs.source }} to main" >> DEPLOYMENT.md

      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: production-deployment-${{ github.run_number }}
          title: "🚀 Production deployment from ${{ github.event.inputs.source }}"
          body: |
            ## Production Deployment
            
            This PR promotes changes from `${{ github.event.inputs.source }}` to production (`main`).
            
            **Source branch:** `${{ github.event.inputs.source }}`
            **Target branch:** `main`
            **Triggered by:** @${{ github.actor }}
            **Workflow run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            ### Changes included:
            - All commits from `${{ github.event.inputs.source }}` branch
            
            ---
            *This PR was created automatically by the Deploy Production workflow.*
          commit-message: "deploy: promote ${{ github.event.inputs.source }} to production"
          delete-branch: true

      - name: No changes to promote
        if: steps.check_changes.outputs.has_changes == 'false'
        run: echo "::notice::No changes to promote from ${{ github.event.inputs.source }} to main. Branches are already in sync."
